package org.openpnp.gui.shell;

/**
 * The design tokens of {@code design/mockups/mock.css} as constants. Generated by
 * {@code tools/design-tokens/generate.ps1} (org.openpnp.gui.theme.DesignTokens in the test
 * sources): do not edit, DesignTokensTest compares this file with the stylesheet.
 * <p>
 * Sizes are CSS pixels at the default 13 pixel body text; radii are radii, so Java2D and
 * FlatLaf, which take a diameter, want twice the number.
 */
public final class Tokens {
    private Tokens() {
    }

    public static final int R_SM = 6;
    public static final int R_MD = 10;
    public static final int R_LG = 14;
    public static final float FS_TITLE = 15f;
    public static final int FW_TITLE = 700;
    public static final float FS_BODY = 13f;
    public static final int FW_BODY = 400;
    public static final float FS_BUTTON = 13f;
    public static final int FW_BUTTON = 500;
    public static final float FS_SECTION = 13f;
    public static final int FW_SECTION = 600;
    public static final float FS_SMALL = 12f;
    public static final int FW_SMALL = 400;
    public static final float FS_TABLE = 12.5f;
    public static final int FW_TABLE = 400;
    public static final float FS_HEADER = 11.5f;
    public static final int FW_HEADER = 600;
    public static final float FS_AUX = 11.5f;
    public static final int FW_AUX = 500;
    public static final float FS_TAG = 11f;
    public static final int FW_TAG = 600;
    public static final float FS_MICRO = 10f;
    public static final int FW_MICRO = 700;
    public static final float FS_DRO = 20f;
    public static final int FW_DRO = 600;
    public static final float FS_DRO_COMPACT = 16f;
    public static final int GAP_CARD = 10;
    public static final int PAD_OVERLAY = 12;
    public static final int PAD_SECTION = 16;
    public static final int FORM_LABEL = 112;
    public static final int H_CONTROL = 32;
    public static final int H_CONTROL_SM = 28;
    public static final int H_CONTROL_XS = 24;
    public static final int H_INPUT = 30;
    public static final int H_ROW = 32;
    public static final int W_RAIL = 68;
    public static final int W_SIDE = 500;
    public static final int H_TOPBAR = 52;
    public static final int H_STATUS = 28;

    /** The colours' theme keys: the same name in both themes. */
    public static final String ACCENT = "Pono.accent";
    public static final String ACCENT_STRONG = "Pono.accentStrong";
    public static final String ACCENT_SOFT = "Pono.accentSoft";
    public static final String OK = "Pono.ok";
    public static final String OK_SOFT = "Pono.okSoft";
    public static final String WARN = "Pono.warn";
    public static final String WARN_SOFT = "Pono.warnSoft";
    public static final String ERR = "Pono.err";
    public static final String ERR_SOFT = "Pono.errSoft";
    public static final String INFO = "Pono.info";
    public static final String BG = "Pono.bg";
    public static final String SURFACE = "Pono.surface";
    public static final String SURFACE_2 = "Pono.surface2";
    public static final String SURFACE_3 = "Pono.surface3";
    public static final String HOVER = "Pono.hover";
    public static final String BORDER = "Pono.border";
    public static final String BORDER_STRONG = "Pono.borderStrong";
    public static final String TEXT = "Pono.text";
    public static final String TEXT_2 = "Pono.text2";
    public static final String MUTED = "Pono.muted";
    public static final String OVERLAY = "Pono.overlay";
    public static final String CAMERA_BG = "Pono.cameraBg";
    public static final String ON_ACCENT = "Pono.onAccent";
}
